import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        background: '#f7f9fb',
        surface: '#f7f9fb',
        'surface-container': '#eceef0',
        'surface-container-low': '#f2f4f6',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'surface-variant': '#e0e3e5',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f7f9fb',
        primary: '#DEFE00',
        'primary-container': '#f3ffb3',
        'primary-fixed': '#c5e000',
        'primary-fixed-dim': '#a4bc00',
        secondary: '#565e74',
        'secondary-container': '#dae2fd',
        'secondary-fixed': '#dae2fd',
        'secondary-fixed-dim': '#bec6e0',
        tertiary: '#505f76',
        'tertiary-container': '#e3edff',
        'tertiary-fixed': '#d3e4fe',
        'tertiary-fixed-dim': '#b7c8e1',
        outline: '#747a60',
        'outline-variant': '#c4c9ac',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-background': '#191c1e',
        'on-surface': '#191c1e',
        'on-surface-variant': '#444933',
        'on-primary': '#191c1e',
        'on-primary-container': '#2a3200',
        'on-primary-fixed': '#000000',
        'on-primary-fixed-variant': '#343d00',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#5c647a',
        'on-secondary-fixed': '#131b2e',
        'on-secondary-fixed-variant': '#3f465c',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#5c6c82',
        'on-tertiary-fixed': '#0b1c30',
        'on-tertiary-fixed-variant': '#38485d',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'inverse-primary': '#9ee7b8',
      },
      fontFamily: {
        'display-lg': ['var(--font-space-grotesk)', 'sans-serif'],
        'headline-lg': ['var(--font-space-grotesk)', 'sans-serif'],
        'headline-md': ['var(--font-space-grotesk)', 'sans-serif'],
        'label-caps': ['var(--font-jetbrains)', 'monospace'],
        'body-lg': ['var(--font-inter)', 'sans-serif'],
        'body-md': ['var(--font-inter)', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['72px', { lineHeight: '72px', letterSpacing: '-0.04em', fontWeight: '800' }],
        'headline-lg': ['48px', { lineHeight: '52px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '28px', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
      spacing: {
        gutter: '24px',
        'margin-desktop': '48px',
        'margin-mobile': '16px',
        'stack-md': '16px',
        'stack-sm': '8px',
        'stack-lg': '32px',
        'container-max': '1280px',
      },
      boxShadow: {
        soft: '0 8px 24px rgba(0,0,0,0.04)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
      },
    },
  },
  plugins: [],
};

export default config;
